apiVersion: v1
kind: Secret
metadata:
  name: schloss-secret
type: Opaque
data:
  TOKEN_VALUE: {{ .Values.secret.tokenValue | b64enc | quote }}
  SHARED_SECRET: {{ .Values.secret.sharedSecret | b64enc | quote }}
