apiVersion: v1
kind: Service
metadata:
  name: schluessel-service
spec:
  selector:
    app: schluessel
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
