[package]
name = "schluessel"
version = "0.1.0"
edition = "2021"
authors = ["Jan-Simon Baudler <janbaudler@gmail.com"]

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.4.0"
env_logger = "0.10.0"
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
