name: schluessel - gha ci

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - "master"

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.4

      - name: Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.0.3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create docker metadata for GHCR
        id: ghcrmeta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/jsbaudler/schluessel
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=${{ format('{0}-{1}', steps.version.outputs.version, steps.version.outputs.increment ) }}
            type=raw,value=${{ steps.version.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ steps.ghcrmeta.outputs.tags }}
          labels: ${{ steps.gcrmeta.outputs.labels }}
          build-args: |
            SCHLOSS_VERSION=${{ format('{0}-{1}', steps.version.outputs.version, steps.version.outputs.increment ) }}
